SUPABASE_URL ="https://gsxnpvwmomhbzbapguwt.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzeG5wdndtb21oYnpiYXBndXd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMDk0ODEsImV4cCI6MjA2OTY4NTQ4MX0.HDJUeBvbrFwBFoRYIX3zeux2eZwbJnXbxMuRTDAvLPw"
GROQ_API_KEY = "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"

